### ISSUE TITLE
How to use it on Astro?

### ISSUE THREAD

**Issue by prakash1763** [XIYO/remark-figure-caption#1]
Can I use this for Astro and how to configure it?

**Comment by XIYO** [comment]
Hello,  
I am a beginner developer. :)  
Thank you for being the first person to report an issue.

I will do my best to help.

This library works behind `remark-parse`.

It seems that the usage guide provided in the README might have been insufficient, given that this issue has been raised.

If you could share the code you are currently using, I would be happy to provide more detailed guidance on how to use it.

Alternatively, if you are trying to apply it to your unique project, I’d be glad to review it with you!

Thank you for your interest. 🥰

**Comment by prakash1763** [comment]
Thanks for replying. I use this configuration:

`npm i remark-figure-caption@latest`

Then I add to Astro config
`astro.config.ts`
```
import { defineConfig } from 'astro/config'
import mdx from '@astrojs/mdx'
import remarkFigure from 'remark-figure-caption'

export default defineConfig({
  base: https://example.com,
  integrations: [
    mdx(),
    remarkFigure(),
    //other plugin
  ],
  markdown: {
    gfm: true,
  }
)}
```

**Comment by XIYO** [comment]
I'm communicating using a translation tool.

Hello,

I had a look at your unique repository.

In your `astro.config.ts` file, you can add:

```ts
import remarkFigureCaption from 'remark-figure-caption'; // You will need to install this new package.

...
  markdown: {
    gfm: true,
    remarkPlugins: [remarkCode, remarkFigureCaption], // Add this code here.
    syntaxHighlight: 'prism',
  },
```

By adding this code, if there is an image with indented content in your MDX files, it will be wrapped with a `<figure>` tag upon rendering.

For example, in your `post-7.mdx` file:

```markdown
---
title: 'Astro Zero'
description: 'A zero styling, simple, Astro blog starter template.'
pubDate: 2024-07-02
image: 'https://picsum.photos/seed/theme-001/960/480'
category: 'Theme'
tags: ['astro', 'guide', 'getting started']
featured: true
---

## example

![image](https://picsum.photos/seed/theme-001/960/480)

> hello world
```

This will be transformed and rendered as:

```html
<figure>
<img src="https://picsum.photos/seed/theme-001/960/480" alt="image">
<figcaption>
   <p>hello world</p>
</figcaption>
</figure>
```

**Comment by prakash1763** [comment]
Thank you! It's worked.
